# Generated by Django 3.1.1 on 2020-10-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_adaugat_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanta',
            name='id_Ecris',
            field=models.IntegerField(unique=True),
        ),
    ]
