export const VideoCallTypes = {
  GET_VIDEOCONFERENCES_BY_DATE_SUCCESS: "GET_VIDEOCONFERENCES_BY_DATE_SUCCESS",
  GET_VIDEOCONFERENCES_BY_DATE_FAIL: "GET_VIDEOCONFERENCES_BY_DATE_FAIL",

  ADD_VIDEOCONFERENCE_STARTED: "ADD_VIDEOCONFERENCE_STARTED",
  ADD_VIDEOCONFERENCE_SUCCESS: "ADD_VIDEOCONFERENCE_SUCCESS",
  ADD_VIDEOCONFERENCE_FAIL: "ADD_VIDEOCONFERENCE_FAIL",

  DELETE_VIDEOCONFERENCE_STARTED: "DELETE_VIDEOCONFERENCE_STARTED",
  DELETE_VIDEOCONFERENCE_SUCCESS: "DELETE_VIDEOCONFERENCE_SUCCESS",
  DELETE_VIDEOCONFERENCE_FAIL: "DELETE_VIDEOCONFERENCE_FAIL",

  APPROVE_VIDEOCONFERENCE_DELETE: "APPROVE_VIDEOCONFERENCE_DELETE",
  DENY_VIDEOCONFERENCE_DELETE: "DENY_VIDEOCONFERENCE_DELETE",

  MODIFY_VIDEOCONFERENCE: "MODIFY_VIDEOCONFERENCE",

  MARK_VIDEOCALL: "MARK_VIDEOCALL",
  UNMARK_VIDEOCALL: "UNMARK_VIDEOCALL",
};
