export const VideoCallTypes = {
  GET_VIDEOCONFERENCES_BY_DATE_SUCCESS: "GET_VIDEOCONFERENCES_BY_DATE_SUCCESS",
  GET_VIDEOCONFERENCES_BY_DATE_FAIL: "GET_VIDEOCONFERENCES_BY_DATE_FAIL",

  ADD_VIDEOCONFERENCE_STARTED: "ADD_VIDEOCONFERENCE_STARTED",
  ADD_VIDEOCONFERENCE_SUCCESS: "ADD_VIDEOCONFERENCE_SUCCESS",
  ADD_VIDEOCONFERENCE_FAIL: "ADD_VIDEOCONFERENCE_FAIL",

  DELETE_VIDEOCONFERENCE: "DELETE_VIDEOCONFERENCE",
  MODIFY_VIDEOCONFERENCE: "MODIFY_VIDEOCONFERENCE",
};
