export const VideoCallTypes = {
  GET_VIDEOCONFERENCES_BY_DATE_SUCCESS: "GET_VIDEOCONFERENCES_BY_DATE_SUCCESS",
  GET_VIDEOCONFERENCES_BY_DATE_FAIL: "GET_VIDEOCONFERENCES_BY_DATE_FAIL",

  ADD_VIDEOCONFERENCE: "ADD_VIDEOCONFERENCE",
  DELETE_VIDEOCONFERENCE: "DELETE_VIDEOCONFERENCE",
  MODIFY_VIDEOCONFERENCE: "MODIFY_VIDEOCONFERENCE",
};
