const UserActionTypes = {
  START_USER_LOG_IN: "START_USER_LOG_IN",
  USER_LOG_IN_SUCCESS: "USER_LOG_IN_SUCCESS",
  USER_LOG_IN_FAILURE: "USER_LOG_IN_FAILURE",

  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_CURRENT_USER: "GET_CURRENT_USER",

  USER_LOG_OUT_SUCCESS: "USER_LOG_OUT_SUCCESS",
  USER_LOG_OUT_FAIL: "USER_LOG_OUT_FAIL",

  AUTHENTICATED_SUCCESS: "AUTHENTICATED_SUCCESS",
  AUTHENTICATED_FAIL: "AUTHENTICATED_FAIL",
};

export default UserActionTypes;
