"""
Django settings for todo project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4$+#te6a40%10h7-rxiwbbamd_00(3r4$+2+dl_cic=xtj^mas'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'flatpickr',
    'todoapp',
    'import_export',
    'users',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todo.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', 'users.custom_backend.CustomBackend', ]


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'usersTRCJ': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '10.15.60.52',
        'USER': 'ecris_readonly',
        'PASSWORD': 'P@ssw0rd384',
        'NAME': 'ecris_cdms',

        'OPTIONS': {
            'driver': 'ODBC Driver 13 for SQL Server',
        },
    },
    'usersJCN': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '10.15.101.22',
        'USER': 'ecris_readonly',
        'PASSWORD': 'P@ssw0rd384',
        'NAME': 'ecris_cdms',

        'OPTIONS': {
            'driver': 'ODBC Driver 13 for SQL Server',
        },
    },
    'usersJD': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '10.15.102.22',
        'USER': 'ecris_readonly',
        'PASSWORD': 'P@ssw0rd384',
        'NAME': 'ecris_cdms',

        'OPTIONS': {
            'driver': 'ODBC Driver 13 for SQL Server',
        },
    },
    'usersJG': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '10.15.103.22',
        'USER': 'ecris_readonly',
        'PASSWORD': 'P@ssw0rd384',
        'NAME': 'ecris_cdms',

        'OPTIONS': {
            'driver': 'ODBC Driver 13 for SQL Server',
        },
    },
    'usersJH': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '10.15.104.22',
        'USER': 'ecris_readonly',
        'PASSWORD': 'P@ssw0rd384',
        'NAME': 'ecris_cdms',

        'OPTIONS': {
            'driver': 'ODBC Driver 13 for SQL Server',
        },
    },
    'usersJT': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': '10.15.105.22',
        'USER': 'ecris_readonly',
        'PASSWORD': 'P@ssw0rd384',
        'NAME': 'ecris_cdms',

        'OPTIONS': {
            'driver': 'ODBC Driver 13 for SQL Server',
        },
    }
}

AUTH_USER_MODEL = 'users.MyUser'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_L10N = False

USE_TZ = True

TIME_FORMAT = 'H:i'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/'
