# Generated by Django 3.1.1 on 2020-10-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20201026_1235'),
        ('users', '0002_myuser_instanta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='instanta',
            field=models.ForeignKey(default=117, on_delete=django.db.models.deletion.CASCADE, to='todoapp.instanta', to_field='id_Ecris'),
            preserve_default=False,
        ),
    ]
